CREATE EXTERNAL TABLE tdp_user_incoming.consoelec (
  operateur String,
  annee String,
  filiere string,
  consoa decimal(10,4),
  pdla integer,
  nombre_maille_secretisees_a integer,
    indquala decimal(10,4),
    consoi decimal(10,4),
    pdli integer,
    nombre_maille_secretisees_i integer,
    indquali decimal(10,4),
    consot decimal(10,4),
    pdlt integer,
    nombre_maille_secretisees_t integer,
    indqualt decimal(10,4),
    consor decimal(10,4),
    pdlr integer,
    nombre_maille_secretisees_r integer,
    indqualr decimal(10,4),
    thermor decimal(10,4),
    partr decimal(10,4),
    consona decimal(10,4),
    pdlna integer,
    nombre_maille_secretisees_na integer,
    indqualna decimal(10,4),
    code_commune String,
    libelle_commune string,
    code_epci string,
    libelle_epci string,
    code_departement string,
    libelle_departement string,
    code_region string,
    libelle_region string,
    id_filiere string,
    consototale decimal(10,4),
    code_postal string
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ';'
LOCATION '/warehouse/incoming/'
tblproperties ("skip.header.line.count"="1");

CREATE TABLE tdp_user_incoming.consoelec_hbase
(
    row_num integer,
    operateur String,
    annee String,
    filiere string,
    consoa decimal(10,4),
    pdla integer,
    nombre_maille_secretisees_a integer,
    indquala decimal(10,4),
    consoi decimal(10,4),
    pdli integer,
    nombre_maille_secretisees_i integer,
    indquali decimal(10,4),
    consot decimal(10,4),
    pdlt integer,
    nombre_maille_secretisees_t integer,
    indqualt decimal(10,4),
    consor decimal(10,4),
    pdlr integer,
    nombre_maille_secretisees_r integer,
    indqualr decimal(10,4),
    thermor decimal(10,4),
    partr decimal(10,4),
    consona decimal(10,4),
    pdlna integer,
    nombre_maille_secretisees_na integer,
    indqualna decimal(10,4),
    code_commune String,
    libelle_commune string,
    code_epci string,
    libelle_epci string,
    code_departement string,
    libelle_departement string,
    code_region string,
    libelle_region string,
    id_filiere string,
    consototale decimal(10,4),
    code_postal string
)
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES ("hbase.columns.mapping" = ":key,
    m:operateur,
    m:annee,
    m:filiere,
    m:consoa#b,
    m:pdla#b,
    m:nombre_maille_secretisees_a#b,
    m:indquala#b,
    m:consoi#b,
    m:pdli#b,
    m:nombre_maille_secretisees_i#b,
    m:indquali#b,
    m:consot#b,
    m:pdlt#b,
    m:nombre_maille_secretisees_t#b,
    m:indqualt#b,
    m:consor#b,
    m:pdlr#b,
    m:nombre_maille_secretisees_r#b,
    m:indqualr#b,
    m:thermor#b,
    m:partr#b,
    m:consona#b,
    m:pdlna#b,
    m:nombre_maille_secretisees_na#b,
    m:indqualna#b,
    m:code_commune,
    m:libelle_commune,
    m:code_epci,
    m:libelle_epci,
    m:code_departement,
    m:libelle_departement,
    m:code_region,
    m:libelle_region,
    m:id_filiere,
    m:consototale#b,
    m:code_postal")
TBLPROPERTIES ("hbase.table.name" = "tdp_user_consoelec"); --, "hbase.table.default.storage.type" = "binary"

INSERT INTO tdp_user_incoming.consoelec_hbase SELECT * FROM tdp_user_incoming.consoelec_id;