# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Install Presto Server
  hosts: presto_server
  tasks:
    - tosit.tdp.resolve:
        node_name: presto_server
    - import_role:
        name: tosit.tdp_extra.presto.server
        tasks_from: install
    - meta: clear_facts
